/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder_19 (
    input rst,
    input [15:0] a,
    input [15:0] b,
    input [5:0] alufn,
    output reg [2:0] zvn,
    output reg [15:0] out
  );
  
  
  
  reg [15:0] s;
  
  always @* begin
    s = 16'h0000;
    if (alufn[0+0-:1] == 1'h0) begin
      s = a + b;
    end
    if (alufn[0+0-:1] == 1'h1) begin
      s = a - b;
    end
    zvn[0+0-:1] = s[15+0-:1];
    zvn[1+0-:1] = (a[15+0-:1] & (b[15+0-:1] ^ alufn[0+0-:1]) & !s[15+0-:1]) | (!a[15+0-:1] & !(b[15+0-:1] ^ alufn[0+0-:1]) & s[15+0-:1]);
    zvn[2+0-:1] = 1'h0;
    if (s == 16'h0000) begin
      zvn[2+0-:1] = 1'h1;
    end
    out = s;
  end
endmodule
