/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module control_fsm_4 (
    input clk,
    input rst,
    input colour_button,
    input confirm_button,
    output reg [15:0] out,
    output reg [19:0] seg_out,
    output reg [15:0] outled
  );
  
  
  
  integer index;
  
  wire [16-1:0] M_alu16_out;
  wire [1-1:0] M_alu16_div_err;
  wire [3-1:0] M_alu16_zvn;
  wire [16-1:0] M_alu16_a_data;
  wire [16-1:0] M_alu16_b_data;
  wire [6-1:0] M_alu16_aluop_signal;
  reg [6-1:0] M_alu16_alufn_signal;
  reg [16-1:0] M_alu16_a;
  reg [16-1:0] M_alu16_b;
  alu_7 alu16 (
    .rst(rst),
    .alufn_signal(M_alu16_alufn_signal),
    .a(M_alu16_a),
    .b(M_alu16_b),
    .out(M_alu16_out),
    .div_err(M_alu16_div_err),
    .zvn(M_alu16_zvn),
    .a_data(M_alu16_a_data),
    .b_data(M_alu16_b_data),
    .aluop_signal(M_alu16_aluop_signal)
  );
  
  wire [16-1:0] M_regfile_ra_data;
  wire [16-1:0] M_regfile_rb_data;
  reg [5-1:0] M_regfile_ra;
  reg [5-1:0] M_regfile_rb;
  reg [5-1:0] M_regfile_rc;
  reg [1-1:0] M_regfile_we;
  reg [16-1:0] M_regfile_wr_data;
  regfile_8 regfile (
    .clk(clk),
    .rst(rst),
    .ra(M_regfile_ra),
    .rb(M_regfile_rb),
    .rc(M_regfile_rc),
    .we(M_regfile_we),
    .wr_data(M_regfile_wr_data),
    .ra_data(M_regfile_ra_data),
    .rb_data(M_regfile_rb_data)
  );
  
  wire [16-1:0] M_sel_mux_asel_out;
  wire [16-1:0] M_sel_mux_bsel_out;
  wire [16-1:0] M_sel_mux_wdsel_out;
  reg [16-1:0] M_sel_mux_ra_data;
  reg [16-1:0] M_sel_mux_rb_data;
  reg [16-1:0] M_sel_mux_alu_data;
  reg [3-1:0] M_sel_mux_asel_signal;
  reg [4-1:0] M_sel_mux_bsel_signal;
  reg [2-1:0] M_sel_mux_wdsel_signal;
  sel_mux_9 sel_mux (
    .ra_data(M_sel_mux_ra_data),
    .rb_data(M_sel_mux_rb_data),
    .alu_data(M_sel_mux_alu_data),
    .asel_signal(M_sel_mux_asel_signal),
    .bsel_signal(M_sel_mux_bsel_signal),
    .wdsel_signal(M_sel_mux_wdsel_signal),
    .asel_out(M_sel_mux_asel_out),
    .bsel_out(M_sel_mux_bsel_out),
    .wdsel_out(M_sel_mux_wdsel_out)
  );
  
  wire [(5'h10+0)-1:0] M_led_out_led;
  reg [(5'h10+0)-1:0] M_led_out_update;
  reg [(5'h10+0)*16-1:0] M_led_out_encode;
  
  genvar GEN_led_out0;
  generate
  for (GEN_led_out0=0;GEN_led_out0<5'h10;GEN_led_out0=GEN_led_out0+1) begin: led_out_gen_0
    led_out_10 led_out (
      .clk(clk),
      .rst(rst),
      .update(M_led_out_update[GEN_led_out0*(1)+(1)-1-:(1)]),
      .encode(M_led_out_encode[GEN_led_out0*(5'h10)+(5'h10)-1-:(5'h10)]),
      .led(M_led_out_led[GEN_led_out0*(1)+(1)-1-:(1)])
    );
  end
  endgenerate
  
  wire [1-1:0] M_slow_clock_value;
  counter_11 slow_clock (
    .clk(clk),
    .rst(rst),
    .value(M_slow_clock_value)
  );
  
  wire [1-1:0] M_slow_edge_out;
  reg [1-1:0] M_slow_edge_in;
  edge_detector_3 slow_edge (
    .clk(clk),
    .in(M_slow_edge_in),
    .out(M_slow_edge_out)
  );
  
  
  localparam IDLE_phase = 7'd0;
  localparam NORMALMODE_phase = 7'd1;
  localparam IMPOSTERMODE_phase = 7'd2;
  localparam ADDGAMEMODE_phase = 7'd3;
  localparam SUBGAMEMODE_phase = 7'd4;
  localparam UPDATEGAMEMODEADD_phase = 7'd5;
  localparam UPDATEGAMEMODESUB_phase = 7'd6;
  localparam POSITION_phase = 7'd7;
  localparam BRANCHCOLOURINDEX_phase = 7'd8;
  localparam INCREASECOLOURINDEX_phase = 7'd9;
  localparam UPDATECOLOURINDEX_phase = 7'd10;
  localparam BACKTOFIRSTCOLOURINDEX_phase = 7'd11;
  localparam UPDATECOLOURPOS0_phase = 7'd12;
  localparam ADDTOGUESSINDEX_phase = 7'd13;
  localparam UPDATEGUESSINDEX_phase = 7'd14;
  localparam SHIFTLEFTGUESSINDEX_phase = 7'd15;
  localparam UPDATESHIFTEDGUESSINDEX_phase = 7'd16;
  localparam BRANCHCHECKPOSITIONINDEX_phase = 7'd17;
  localparam INCREASEPOSITIONINDEX_phase = 7'd18;
  localparam UPDATEPOSITIONINDEX_phase = 7'd19;
  localparam FINISH_phase = 7'd20;
  localparam ANDLEDSTRIP_phase = 7'd21;
  localparam SHIFTCOLOUR_phase = 7'd22;
  localparam UPDATELEDCOLOUR_phase = 7'd23;
  localparam UPDATEPHASETWOLED_phase = 7'd24;
  localparam SHIFTXORHELPER_phase = 7'd25;
  localparam UPDATEXORHELPER_phase = 7'd26;
  localparam XOR_phase = 7'd27;
  localparam BRANCHSHIFTCOLOURPOSITION_phase = 7'd28;
  localparam SHIFTCOLOUR0_phase = 7'd29;
  localparam SHIFTCOLOUR1_phase = 7'd30;
  localparam SHIFTCOLOUR2_phase = 7'd31;
  localparam SHIFTCOLOUR3_phase = 7'd32;
  localparam SHIFTGUESSATTEMPTCOUNT_phase = 7'd33;
  localparam UPDATEGUESSATTEMPTCOUNT_phase = 7'd34;
  localparam GETGUESS_phase = 7'd35;
  localparam GETCODE_phase = 7'd36;
  localparam CHECKGUESS_CORRCODE_phase = 7'd37;
  localparam SHIFTHINTRED_phase = 7'd38;
  localparam UPDATEHINTRED_phase = 7'd39;
  localparam SHIFTGUESSHELPERDEFAULT_phase = 7'd40;
  localparam UPDATEGUESSHELPERDEFAULT_phase = 7'd41;
  localparam SHIFTCODEHELPER_phase = 7'd42;
  localparam UPDATECODEHELPER_phase = 7'd43;
  localparam CHECKCODEHELPER_phase = 7'd44;
  localparam SHIFTNOHINT_phase = 7'd45;
  localparam UPDATENOHINT_phase = 7'd46;
  localparam GETNEXTCODE_phase = 7'd47;
  localparam SHIFTTEMPGUESS_phase = 7'd48;
  localparam UPDATETEMPGUESS_phase = 7'd49;
  localparam CHECKTEMPGUESS_TEMPCODE_phase = 7'd50;
  localparam SHIFTHINTWHITE_phase = 7'd51;
  localparam UPDATEHINTWHITE_phase = 7'd52;
  localparam SHIFTCODEHELPERDEFAULT_phase = 7'd53;
  localparam UPDATECODEHELPERDEFAULT_phase = 7'd54;
  localparam COMPARETEMPCOUNTER_phase = 7'd55;
  localparam ADDTEMPCOUNTER_phase = 7'd56;
  localparam UPDATETEMPCOUNTER_phase = 7'd57;
  localparam CHECKGAMEMODE_phase = 7'd58;
  localparam ADDIMPOSTER_phase = 7'd59;
  localparam UPDATEIMPOSTER_phase = 7'd60;
  localparam COMPARECODE_GUESS_phase = 7'd61;
  localparam SHIFTATTEMPTCOUNT_phase = 7'd62;
  localparam UPDATEATTEMPTCOUNT_phase = 7'd63;
  localparam BRANCHATTEMPTCOUNT_phase = 7'd64;
  localparam UPDATEHINTLED_phase = 7'd65;
  localparam RESETPOSITION_phase = 7'd66;
  localparam RESETCOLOUR_phase = 7'd67;
  localparam RESETHINT_phase = 7'd68;
  localparam RESETCOUNTER_phase = 7'd69;
  localparam RESETATTEMPT_phase = 7'd70;
  localparam RESETLEDCOLOUR_phase = 7'd71;
  localparam RESETXORHELPER_phase = 7'd72;
  localparam RESETALLLED_phase = 7'd73;
  localparam RESETGAMEMODE_phase = 7'd74;
  localparam RESETGUESS_phase = 7'd75;
  localparam RESETPOSITIONFINAL_phase = 7'd76;
  localparam RESETCOLOURFINAL_phase = 7'd77;
  localparam RESETHINTFINAL_phase = 7'd78;
  localparam RESETCOUNTERFINAL_phase = 7'd79;
  localparam RESETATTEMPTFINAL_phase = 7'd80;
  localparam RESETLEDCOLOURFINAL_phase = 7'd81;
  localparam RESETXORHELPERFINAL_phase = 7'd82;
  localparam RESETGUESSFINAL_phase = 7'd83;
  localparam LOSE_phase = 7'd84;
  localparam WIN_phase = 7'd85;
  localparam GAMEOVER_phase = 7'd86;
  
  reg [6:0] M_phase_d, M_phase_q = IDLE_phase;
  
  always @* begin
    M_phase_d = M_phase_q;
    
    M_regfile_ra = 4'h0;
    M_regfile_rb = 4'h0;
    M_regfile_rc = 4'h0;
    M_regfile_we = 1'h0;
    M_regfile_wr_data = 1'h0;
    M_alu16_alufn_signal = 6'h00;
    M_sel_mux_asel_signal = 2'h0;
    M_sel_mux_bsel_signal = 3'h0;
    M_sel_mux_wdsel_signal = 2'h0;
    M_sel_mux_ra_data = M_regfile_ra_data;
    M_sel_mux_rb_data = M_regfile_rb_data;
    M_alu16_a = M_sel_mux_asel_out;
    M_alu16_b = M_sel_mux_bsel_out;
    M_sel_mux_alu_data = M_alu16_out;
    M_regfile_wr_data = M_sel_mux_wdsel_out;
    out = 16'h0000;
    seg_out = 20'h00000;
    M_slow_edge_in = M_slow_clock_value;
    M_led_out_update = 16'h0000;
    M_led_out_encode = 256'h0000000000000000000000000000000000000000000000000000000000000000;
    outled = M_led_out_led;
    
    case (M_phase_q)
      IDLE_phase: begin
        seg_out = 20'h0be0d;
        if (confirm_button) begin
          M_phase_d = NORMALMODE_phase;
        end
      end
      NORMALMODE_phase: begin
        seg_out = 20'hb59c1;
        if (colour_button) begin
          M_phase_d = ADDGAMEMODE_phase;
        end else begin
          if (confirm_button) begin
            M_phase_d = POSITION_phase;
          end
        end
      end
      ADDGAMEMODE_phase: begin
        seg_out = 20'h519c0;
        M_regfile_ra = 4'h4;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 1'h0;
        M_sel_mux_bsel_signal = 2'h2;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_a = M_sel_mux_asel_out;
        M_alu16_b = M_sel_mux_bsel_out;
        M_alu16_alufn_signal = 6'h00;
        M_regfile_rc = 4'hf;
        M_regfile_we = 1'h1;
        M_phase_d = UPDATEGAMEMODEADD_phase;
      end
      UPDATEGAMEMODEADD_phase: begin
        seg_out = 20'h554ce;
        M_regfile_ra = 4'hf;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 1'h0;
        M_sel_mux_bsel_signal = 1'h0;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_a = M_sel_mux_asel_out;
        M_alu16_b = M_sel_mux_bsel_out;
        M_alu16_alufn_signal = 6'h1a;
        M_regfile_rc = 4'h4;
        M_regfile_we = 1'h1;
        out = M_sel_mux_asel_out;
        M_phase_d = IMPOSTERMODE_phase;
      end
      IMPOSTERMODE_phase: begin
        seg_out = 20'hb59c2;
        if (colour_button) begin
          M_phase_d = SUBGAMEMODE_phase;
        end else begin
          if (confirm_button) begin
            M_phase_d = POSITION_phase;
          end
        end
      end
      SUBGAMEMODE_phase: begin
        seg_out = 20'h519c0;
        M_regfile_ra = 4'h4;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 1'h0;
        M_sel_mux_bsel_signal = 2'h2;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_a = M_sel_mux_asel_out;
        M_alu16_b = M_sel_mux_bsel_out;
        M_alu16_alufn_signal = 6'h01;
        M_regfile_rc = 4'hf;
        M_regfile_we = 1'h1;
        M_phase_d = UPDATEGAMEMODESUB_phase;
      end
      UPDATEGAMEMODESUB_phase: begin
        seg_out = 20'h954ce;
        M_regfile_ra = 4'hf;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 1'h0;
        M_sel_mux_bsel_signal = 1'h0;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_a = M_sel_mux_asel_out;
        M_alu16_b = M_sel_mux_bsel_out;
        M_alu16_alufn_signal = 6'h1a;
        M_regfile_rc = 4'h4;
        M_regfile_we = 1'h1;
        out = M_sel_mux_asel_out;
        M_phase_d = NORMALMODE_phase;
      end
      POSITION_phase: begin
        seg_out = 20'h055d0;
        M_regfile_ra = 4'he;
        M_regfile_rb = 4'h3;
        M_sel_mux_asel_signal = 2'h0;
        M_sel_mux_bsel_signal = 3'h0;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h1a;
        M_regfile_rc = 4'h0;
        M_regfile_we = 1'h0;
        M_led_out_encode = {5'h10{{M_sel_mux_asel_out}}};
        out = M_sel_mux_asel_out;
        for (index = 1'h0; index < 5'h10; index = index + 1) begin
          M_led_out_update[(index)*1+0-:1] = M_sel_mux_bsel_out[(index)*1+0-:1];
        end
        M_phase_d = BACKTOFIRSTCOLOURINDEX_phase;
      end
      BRANCHCOLOURINDEX_phase: begin
        seg_out = 20'h02d81;
        M_regfile_ra = 4'h2;
        M_sel_mux_asel_signal = 1'h0;
        M_sel_mux_bsel_signal = 3'h7;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_a = M_sel_mux_asel_out;
        M_alu16_b = M_sel_mux_bsel_out;
        M_alu16_alufn_signal = 6'h35;
        if (M_sel_mux_wdsel_out) begin
          M_phase_d = INCREASECOLOURINDEX_phase;
        end else begin
          M_phase_d = BACKTOFIRSTCOLOURINDEX_phase;
        end
      end
      INCREASECOLOURINDEX_phase: begin
        seg_out = 20'h00581;
        M_regfile_ra = 4'h2;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 1'h0;
        M_sel_mux_bsel_signal = 3'h2;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_a = M_sel_mux_asel_out;
        M_alu16_b = M_sel_mux_bsel_out;
        M_alu16_alufn_signal = 6'h00;
        M_regfile_rc = 4'hf;
        M_regfile_we = 1'h1;
        M_phase_d = UPDATECOLOURINDEX_phase;
      end
      UPDATECOLOURINDEX_phase: begin
        seg_out = 20'h05581;
        M_regfile_ra = 4'hf;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 1'h0;
        M_sel_mux_bsel_signal = 1'h0;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_a = M_sel_mux_asel_out;
        M_alu16_b = M_sel_mux_bsel_out;
        M_alu16_alufn_signal = 6'h1a;
        M_regfile_rc = 4'h2;
        M_regfile_we = 1'h1;
        out = M_sel_mux_asel_out;
        M_phase_d = XOR_phase;
      end
      XOR_phase: begin
        seg_out = 20'h05014;
        M_regfile_ra = 4'hd;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 1'h0;
        M_sel_mux_bsel_signal = 4'he;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_a = M_sel_mux_asel_out;
        M_alu16_b = M_sel_mux_bsel_out;
        M_alu16_alufn_signal = 6'h16;
        M_regfile_rc = 4'hf;
        M_regfile_we = 1'h1;
        out = M_sel_mux_wdsel_out;
        M_phase_d = ANDLEDSTRIP_phase;
      end
      ANDLEDSTRIP_phase: begin
        seg_out = 20'h02a12;
        M_regfile_ra = 4'h7;
        M_regfile_rb = 4'hf;
        M_sel_mux_asel_signal = 1'h0;
        M_sel_mux_bsel_signal = 1'h0;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_a = M_sel_mux_asel_out;
        M_alu16_b = M_sel_mux_bsel_out;
        M_alu16_alufn_signal = 6'h18;
        M_regfile_rc = 4'he;
        M_regfile_we = 1'h1;
        out = M_sel_mux_wdsel_out;
        M_phase_d = BRANCHSHIFTCOLOURPOSITION_phase;
      end
      BRANCHSHIFTCOLOURPOSITION_phase: begin
        seg_out = 20'h5c993;
        M_regfile_ra = 4'h1;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 1'h0;
        M_sel_mux_bsel_signal = 1'h0;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_a = M_sel_mux_asel_out;
        M_alu16_b = M_sel_mux_bsel_out;
        M_alu16_alufn_signal = 6'h1a;
        M_regfile_rc = 4'hf;
        M_regfile_we = 1'h0;
        out = M_sel_mux_wdsel_out;
        if (M_sel_mux_wdsel_out == 1'h0) begin
          M_phase_d = SHIFTCOLOUR0_phase;
        end else begin
          if (M_sel_mux_wdsel_out == 1'h1) begin
            M_phase_d = SHIFTCOLOUR1_phase;
          end else begin
            if (M_sel_mux_wdsel_out == 2'h2) begin
              M_phase_d = SHIFTCOLOUR2_phase;
            end else begin
              if (M_sel_mux_wdsel_out == 2'h3) begin
                M_phase_d = SHIFTCOLOUR3_phase;
              end
            end
          end
        end
      end
      SHIFTCOLOUR0_phase: begin
        seg_out = 20'h93a00;
        M_regfile_ra = 4'h2;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 1'h0;
        M_sel_mux_bsel_signal = 4'hc;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_a = M_sel_mux_asel_out;
        M_alu16_b = M_sel_mux_bsel_out;
        M_alu16_alufn_signal = 6'h20;
        M_regfile_rc = 4'hf;
        M_regfile_we = 1'h1;
        out = M_sel_mux_wdsel_out;
        M_phase_d = UPDATELEDCOLOUR_phase;
      end
      SHIFTCOLOUR1_phase: begin
        seg_out = 20'h93a01;
        M_regfile_ra = 4'h2;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 1'h0;
        M_sel_mux_bsel_signal = 4'h8;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_a = M_sel_mux_asel_out;
        M_alu16_b = M_sel_mux_bsel_out;
        M_alu16_alufn_signal = 6'h20;
        M_regfile_rc = 4'hf;
        M_regfile_we = 1'h1;
        out = M_sel_mux_wdsel_out;
        M_phase_d = UPDATELEDCOLOUR_phase;
      end
      SHIFTCOLOUR2_phase: begin
        seg_out = 20'h93a02;
        M_regfile_ra = 4'h2;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 1'h0;
        M_sel_mux_bsel_signal = 3'h4;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_a = M_sel_mux_asel_out;
        M_alu16_b = M_sel_mux_bsel_out;
        M_alu16_alufn_signal = 6'h20;
        M_regfile_rc = 4'hf;
        M_regfile_we = 1'h1;
        out = M_sel_mux_wdsel_out;
        M_phase_d = UPDATELEDCOLOUR_phase;
      end
      SHIFTCOLOUR3_phase: begin
        seg_out = 20'h93a03;
        M_regfile_ra = 4'h2;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 1'h0;
        M_sel_mux_bsel_signal = 1'h0;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_a = M_sel_mux_asel_out;
        M_alu16_b = M_sel_mux_bsel_out;
        M_alu16_alufn_signal = 6'h1a;
        M_regfile_rc = 4'hf;
        M_regfile_we = 1'h1;
        out = M_sel_mux_wdsel_out;
        M_phase_d = UPDATELEDCOLOUR_phase;
      end
      UPDATELEDCOLOUR_phase: begin
        seg_out = 20'hac260;
        M_regfile_ra = 4'hf;
        M_regfile_rb = 4'he;
        M_sel_mux_asel_signal = 2'h0;
        M_sel_mux_bsel_signal = 3'h0;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h00;
        M_regfile_rc = 4'h7;
        M_regfile_we = 1'h1;
        M_phase_d = UPDATEPHASETWOLED_phase;
      end
      UPDATEPHASETWOLED_phase: begin
        seg_out = 20'h05590;
        M_regfile_ra = 4'h7;
        M_regfile_rb = 4'h3;
        M_sel_mux_asel_signal = 2'h0;
        M_sel_mux_bsel_signal = 3'h0;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h00;
        M_regfile_rc = 4'h0;
        M_regfile_we = 1'h0;
        M_led_out_encode = {5'h10{{M_sel_mux_asel_out}}};
        out = M_sel_mux_asel_out;
        for (index = 1'h0; index < 5'h10; index = index + 1) begin
          M_led_out_update[(index)*1+0-:1] = M_sel_mux_bsel_out[(index)*1+0-:1];
        end
        if (confirm_button) begin
          M_phase_d = BRANCHCHECKPOSITIONINDEX_phase;
        end else begin
          if (colour_button) begin
            M_phase_d = BRANCHCOLOURINDEX_phase;
          end
        end
      end
      BACKTOFIRSTCOLOURINDEX_phase: begin
        seg_out = 20'h5c581;
        M_regfile_ra = 4'h0;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 2'h3;
        M_sel_mux_bsel_signal = 1'h0;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_a = M_sel_mux_asel_out;
        M_alu16_b = M_sel_mux_bsel_out;
        M_alu16_alufn_signal = 6'h1a;
        M_regfile_rc = 4'hf;
        M_regfile_we = 1'h1;
        M_phase_d = UPDATECOLOURINDEX_phase;
      end
      BRANCHCHECKPOSITIONINDEX_phase: begin
        seg_out = 20'h5b261;
        M_regfile_ra = 4'h1;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 1'h0;
        M_sel_mux_bsel_signal = 3'h3;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_a = M_sel_mux_asel_out;
        M_alu16_b = M_sel_mux_bsel_out;
        M_alu16_alufn_signal = 6'h35;
        M_regfile_rc = 4'h0;
        M_regfile_we = 1'h0;
        if (M_sel_mux_wdsel_out) begin
          M_phase_d = INCREASEPOSITIONINDEX_phase;
        end else begin
          M_phase_d = SHIFTGUESSATTEMPTCOUNT_phase;
        end
      end
      INCREASEPOSITIONINDEX_phase: begin
        seg_out = 20'h00661;
        M_regfile_ra = 4'h1;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 1'h0;
        M_sel_mux_bsel_signal = 3'h2;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_a = M_sel_mux_asel_out;
        M_alu16_b = M_sel_mux_bsel_out;
        M_alu16_alufn_signal = 6'h00;
        M_regfile_rc = 4'hf;
        M_regfile_we = 1'h1;
        M_phase_d = UPDATEPOSITIONINDEX_phase;
      end
      UPDATEPOSITIONINDEX_phase: begin
        seg_out = 20'h05661;
        M_regfile_ra = 4'hf;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 1'h0;
        M_sel_mux_bsel_signal = 1'h0;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_a = M_sel_mux_asel_out;
        M_alu16_b = M_sel_mux_bsel_out;
        M_alu16_alufn_signal = 6'h1a;
        M_regfile_rc = 4'h1;
        M_regfile_we = 1'h1;
        M_phase_d = SHIFTXORHELPER_phase;
      end
      SHIFTXORHELPER_phase: begin
        seg_out = 20'h049d4;
        M_regfile_ra = 4'hd;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 1'h0;
        M_sel_mux_bsel_signal = 3'h4;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_a = M_sel_mux_asel_out;
        M_alu16_b = M_sel_mux_bsel_out;
        M_alu16_alufn_signal = 6'h21;
        M_regfile_rc = 4'hf;
        M_regfile_we = 1'h1;
        out = M_sel_mux_wdsel_out;
        M_phase_d = UPDATEXORHELPER_phase;
      end
      UPDATEXORHELPER_phase: begin
        seg_out = 20'hac9d4;
        M_regfile_ra = 4'hf;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 1'h0;
        M_sel_mux_bsel_signal = 3'h4;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_a = M_sel_mux_asel_out;
        M_alu16_b = M_sel_mux_bsel_out;
        M_alu16_alufn_signal = 6'h1a;
        M_regfile_rc = 4'hd;
        M_regfile_we = 1'h1;
        out = M_sel_mux_wdsel_out;
        M_phase_d = BACKTOFIRSTCOLOURINDEX_phase;
      end
      SHIFTGUESSATTEMPTCOUNT_phase: begin
        seg_out = 20'h9194c;
        M_regfile_ra = 4'h3;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 2'h0;
        M_sel_mux_bsel_signal = 4'h2;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h21;
        M_regfile_rc = 4'hf;
        M_regfile_we = 1'h1;
        out = M_sel_mux_wdsel_out;
        M_phase_d = UPDATEGUESSATTEMPTCOUNT_phase;
      end
      UPDATEGUESSATTEMPTCOUNT_phase: begin
        seg_out = 20'ha994c;
        M_regfile_ra = 4'hf;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 2'h0;
        M_sel_mux_bsel_signal = 4'h0;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h1a;
        M_regfile_rc = 4'h3;
        M_regfile_we = 1'h1;
        out = M_sel_mux_wdsel_out;
        M_phase_d = FINISH_phase;
      end
      FINISH_phase: begin
        seg_out = 20'h8864e;
        M_regfile_ra = 4'h7;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 1'h0;
        M_sel_mux_bsel_signal = 3'h4;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_a = M_sel_mux_asel_out;
        M_alu16_b = M_sel_mux_bsel_out;
        M_alu16_alufn_signal = 6'h1a;
        M_regfile_rc = 4'h0;
        M_regfile_we = 1'h0;
        out = M_sel_mux_wdsel_out;
        M_phase_d = GETGUESS_phase;
      end
      GETGUESS_phase: begin
        seg_out = 20'h00001;
        M_regfile_ra = 4'h7;
        M_regfile_rb = 4'h8;
        M_sel_mux_asel_signal = 2'h0;
        M_sel_mux_bsel_signal = 4'h0;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h18;
        M_regfile_rc = 4'hb;
        M_regfile_we = 1'h1;
        out = M_sel_mux_asel_out;
        M_phase_d = GETCODE_phase;
      end
      GETCODE_phase: begin
        seg_out = 20'h00002;
        M_regfile_ra = 4'h5;
        M_regfile_rb = 4'h6;
        M_sel_mux_asel_signal = 2'h0;
        M_sel_mux_bsel_signal = 4'h0;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h18;
        M_regfile_rc = 4'ha;
        M_regfile_we = 1'h1;
        M_phase_d = CHECKGUESS_CORRCODE_phase;
      end
      CHECKGUESS_CORRCODE_phase: begin
        seg_out = 20'h6318c;
        M_regfile_ra = 4'ha;
        M_regfile_rb = 4'hb;
        M_sel_mux_asel_signal = 2'h0;
        M_sel_mux_bsel_signal = 4'h0;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h33;
        M_regfile_rc = 4'h0;
        M_regfile_we = 1'h0;
        if (M_sel_mux_wdsel_out == 16'h0001) begin
          M_phase_d = SHIFTHINTRED_phase;
        end else begin
          M_phase_d = SHIFTCODEHELPER_phase;
        end
      end
      SHIFTHINTRED_phase: begin
        seg_out = 20'h049d4;
        M_regfile_ra = 4'h9;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 2'h0;
        M_sel_mux_bsel_signal = 4'h4;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h23;
        M_regfile_rc = 4'hf;
        M_regfile_we = 1'h1;
        M_phase_d = UPDATEHINTRED_phase;
      end
      UPDATEHINTRED_phase: begin
        seg_out = 20'h049d4;
        M_regfile_ra = 4'hf;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 2'h0;
        M_sel_mux_bsel_signal = 4'h3;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h00;
        M_regfile_rc = 4'h9;
        M_regfile_we = 1'h1;
        M_phase_d = SHIFTGUESSHELPERDEFAULT_phase;
      end
      SHIFTCODEHELPER_phase: begin
        seg_out = 20'h0498e;
        M_regfile_ra = 4'h6;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 2'h0;
        M_sel_mux_bsel_signal = 4'h4;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h23;
        M_regfile_rc = 4'hf;
        M_regfile_we = 1'h1;
        M_phase_d = UPDATECODEHELPER_phase;
      end
      UPDATECODEHELPER_phase: begin
        seg_out = 20'h0558e;
        M_regfile_ra = 4'hf;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 2'h0;
        M_sel_mux_bsel_signal = 4'h0;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h1a;
        M_regfile_rc = 4'h6;
        M_regfile_we = 1'h1;
        M_phase_d = CHECKCODEHELPER_phase;
      end
      CHECKCODEHELPER_phase: begin
        seg_out = 20'h0318e;
        M_regfile_ra = 4'h6;
        M_regfile_rb = 4'h8;
        M_sel_mux_asel_signal = 2'h0;
        M_sel_mux_bsel_signal = 4'h0;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h33;
        M_regfile_rc = 4'h0;
        M_regfile_we = 1'h0;
        if (M_sel_mux_wdsel_out == 16'h0001) begin
          M_phase_d = SHIFTNOHINT_phase;
        end else begin
          M_phase_d = GETNEXTCODE_phase;
        end
      end
      SHIFTNOHINT_phase: begin
        seg_out = 20'h0000e;
        M_regfile_ra = 4'h9;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 2'h0;
        M_sel_mux_bsel_signal = 4'h4;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h23;
        M_regfile_rc = 4'hf;
        M_regfile_we = 1'h1;
        M_phase_d = UPDATENOHINT_phase;
      end
      UPDATENOHINT_phase: begin
        seg_out = 20'ha800e;
        M_regfile_ra = 4'hf;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 2'h0;
        M_sel_mux_bsel_signal = 4'h0;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h1a;
        M_regfile_rc = 4'h9;
        M_regfile_we = 1'h1;
        M_phase_d = SHIFTGUESSHELPERDEFAULT_phase;
      end
      GETNEXTCODE_phase: begin
        seg_out = 20'h00003;
        M_regfile_ra = 4'h5;
        M_regfile_rb = 4'h6;
        M_sel_mux_asel_signal = 2'h0;
        M_sel_mux_bsel_signal = 4'h0;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h18;
        M_regfile_rc = 4'ha;
        M_regfile_we = 1'h1;
        M_phase_d = SHIFTTEMPGUESS_phase;
      end
      SHIFTTEMPGUESS_phase: begin
        seg_out = 20'h00012;
        M_regfile_ra = 4'hb;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 2'h0;
        M_sel_mux_bsel_signal = 4'h4;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h23;
        M_regfile_rc = 4'hf;
        M_regfile_we = 1'h1;
        M_phase_d = UPDATETEMPGUESS_phase;
      end
      UPDATETEMPGUESS_phase: begin
        seg_out = 20'h0540c;
        M_regfile_ra = 4'hf;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 2'h0;
        M_sel_mux_bsel_signal = 4'h0;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 16'h001a;
        M_regfile_rc = 4'hb;
        M_regfile_we = 1'h1;
        M_phase_d = CHECKTEMPGUESS_TEMPCODE_phase;
      end
      CHECKTEMPGUESS_TEMPCODE_phase: begin
        seg_out = 20'h0300c;
        M_regfile_ra = 4'ha;
        M_regfile_rb = 4'hb;
        M_sel_mux_asel_signal = 2'h0;
        M_sel_mux_bsel_signal = 4'h0;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h33;
        M_regfile_rc = 4'h0;
        M_regfile_we = 1'h0;
        if (M_sel_mux_wdsel_out == 16'h0001) begin
          M_phase_d = SHIFTHINTWHITE_phase;
        end else begin
          M_phase_d = SHIFTCODEHELPER_phase;
        end
      end
      SHIFTHINTWHITE_phase: begin
        seg_out = 20'h049ce;
        M_regfile_ra = 4'h9;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 2'h0;
        M_sel_mux_bsel_signal = 4'h4;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h23;
        M_regfile_rc = 4'hf;
        M_regfile_we = 1'h1;
        M_phase_d = UPDATEHINTWHITE_phase;
      end
      UPDATEHINTWHITE_phase: begin
        seg_out = 20'h029ce;
        M_regfile_ra = 4'hf;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 2'h0;
        M_sel_mux_bsel_signal = 4'h2;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h00;
        M_regfile_rc = 4'h9;
        M_regfile_we = 1'h1;
        M_phase_d = SHIFTGUESSHELPERDEFAULT_phase;
      end
      SHIFTGUESSHELPERDEFAULT_phase: begin
        seg_out = 20'h031cf;
        M_regfile_ra = 4'h8;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 2'h0;
        M_sel_mux_bsel_signal = 4'h4;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h24;
        M_regfile_rc = 4'hf;
        M_regfile_we = 1'h1;
        M_phase_d = UPDATEGUESSHELPERDEFAULT_phase;
      end
      UPDATEGUESSHELPERDEFAULT_phase: begin
        seg_out = 20'h055cf;
        M_regfile_ra = 4'hf;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 2'h0;
        M_sel_mux_bsel_signal = 4'h0;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h1a;
        M_regfile_rc = 4'h8;
        M_regfile_we = 1'h1;
        M_phase_d = UPDATECODEHELPERDEFAULT_phase;
      end
      UPDATECODEHELPERDEFAULT_phase: begin
        seg_out = 20'h0318f;
        M_regfile_ra = 4'h8;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 2'h0;
        M_sel_mux_bsel_signal = 4'h0;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h1a;
        M_regfile_rc = 4'h6;
        M_regfile_we = 1'h1;
        M_phase_d = COMPARETEMPCOUNTER_phase;
      end
      COMPARETEMPCOUNTER_phase: begin
        seg_out = 20'h6302c;
        M_regfile_ra = 4'hc;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 2'h0;
        M_sel_mux_bsel_signal = 4'h4;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h33;
        M_regfile_rc = 4'h0;
        M_regfile_we = 1'h0;
        if (M_sel_mux_wdsel_out == 16'h0001) begin
          M_phase_d = CHECKGAMEMODE_phase;
        end else begin
          M_phase_d = ADDTEMPCOUNTER_phase;
        end
      end
      ADDTEMPCOUNTER_phase: begin
        seg_out = 20'h53180;
        M_regfile_ra = 4'hc;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 2'h0;
        M_sel_mux_bsel_signal = 4'h2;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h00;
        M_regfile_rc = 4'hf;
        M_regfile_we = 1'h1;
        M_phase_d = UPDATETEMPCOUNTER_phase;
      end
      UPDATETEMPCOUNTER_phase: begin
        seg_out = 20'hab18c;
        M_regfile_ra = 4'hf;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 2'h0;
        M_sel_mux_bsel_signal = 4'h0;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h1a;
        M_regfile_rc = 4'hc;
        M_regfile_we = 1'h1;
        M_phase_d = GETGUESS_phase;
      end
      CHECKGAMEMODE_phase: begin
        seg_out = 20'h630ce;
        M_regfile_ra = 4'h4;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 2'h0;
        M_sel_mux_bsel_signal = 4'h2;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h33;
        M_regfile_rc = 4'h0;
        M_regfile_we = 1'h0;
        if (M_sel_mux_wdsel_out == 16'h0001) begin
          M_phase_d = ADDIMPOSTER_phase;
        end else begin
          M_phase_d = UPDATEHINTLED_phase;
        end
      end
      ADDIMPOSTER_phase: begin
        seg_out = 20'h52821;
        M_regfile_ra = 4'h9;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 2'h0;
        M_sel_mux_bsel_signal = 4'h3;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h1e;
        M_regfile_rc = 4'hf;
        M_regfile_we = 1'h1;
        out = M_sel_mux_asel_out;
        M_phase_d = UPDATEIMPOSTER_phase;
      end
      UPDATEIMPOSTER_phase: begin
        seg_out = 20'ha8421;
        M_regfile_ra = 4'hf;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 2'h0;
        M_sel_mux_bsel_signal = 4'h0;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h1a;
        M_regfile_rc = 4'h9;
        M_regfile_we = 1'h1;
        out = M_sel_mux_asel_out;
        M_phase_d = UPDATEHINTLED_phase;
      end
      UPDATEHINTLED_phase: begin
        seg_out = 20'hab82d;
        M_regfile_ra = 4'h9;
        M_regfile_rb = 4'h3;
        M_sel_mux_asel_signal = 2'h0;
        M_sel_mux_bsel_signal = 4'h0;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h1a;
        M_regfile_rc = 4'h0;
        M_regfile_we = 1'h0;
        M_led_out_encode = {5'h10{{M_sel_mux_asel_out}}};
        out = M_sel_mux_asel_out;
        for (index = 1'h0; index < 5'h10; index = index + 1) begin
          M_led_out_update[(index)*1+0-:1] = M_sel_mux_bsel_out[(index)*1+0-:1];
        end
        M_phase_d = COMPARECODE_GUESS_phase;
      end
      COMPARECODE_GUESS_phase: begin
        seg_out = 20'h6318c;
        M_regfile_ra = 4'h5;
        M_regfile_rb = 4'h7;
        M_sel_mux_asel_signal = 2'h0;
        M_sel_mux_bsel_signal = 4'h0;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h33;
        M_regfile_rc = 4'h0;
        M_regfile_we = 1'h0;
        if (M_sel_mux_wdsel_out == 16'h0001) begin
          M_phase_d = WIN_phase;
        end else begin
          M_phase_d = SHIFTATTEMPTCOUNT_phase;
        end
      end
      SHIFTATTEMPTCOUNT_phase: begin
        seg_out = 20'h5298c;
        M_regfile_ra = 4'h3;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 2'h0;
        M_sel_mux_bsel_signal = 4'h2;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h21;
        M_regfile_rc = 4'hf;
        M_regfile_we = 1'h1;
        out = M_sel_mux_wdsel_out;
        M_phase_d = UPDATEATTEMPTCOUNT_phase;
      end
      UPDATEATTEMPTCOUNT_phase: begin
        seg_out = 20'haa98c;
        M_regfile_ra = 4'hf;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 2'h0;
        M_sel_mux_bsel_signal = 4'h0;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h1a;
        M_regfile_rc = 4'h3;
        M_regfile_we = 1'h1;
        out = M_sel_mux_wdsel_out;
        M_phase_d = BRANCHATTEMPTCOUNT_phase;
      end
      BRANCHATTEMPTCOUNT_phase: begin
        seg_out = 20'h5314c;
        M_regfile_ra = 4'h3;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 2'h0;
        M_sel_mux_bsel_signal = 4'h1;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h33;
        M_regfile_rc = 4'h0;
        M_regfile_we = 1'h0;
        if (M_sel_mux_wdsel_out == 16'h0001) begin
          M_phase_d = LOSE_phase;
        end else begin
          M_phase_d = RESETPOSITION_phase;
        end
      end
      RESETPOSITION_phase: begin
        seg_out = 20'ha5281;
        M_regfile_ra = 4'h0;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 2'h2;
        M_sel_mux_bsel_signal = 4'h0;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h1a;
        M_regfile_rc = 4'h1;
        M_regfile_we = 1'h1;
        out = M_sel_mux_wdsel_out;
        M_phase_d = RESETCOLOUR_phase;
      end
      RESETCOLOUR_phase: begin
        seg_out = 20'ha5282;
        M_regfile_ra = 4'h0;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 2'h3;
        M_sel_mux_bsel_signal = 4'h0;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h1a;
        M_regfile_rc = 4'h2;
        M_regfile_we = 1'h1;
        out = M_sel_mux_wdsel_out;
        M_phase_d = RESETHINT_phase;
      end
      RESETHINT_phase: begin
        seg_out = 20'ha5283;
        M_regfile_ra = 4'h0;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 2'h2;
        M_sel_mux_bsel_signal = 4'h0;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h1a;
        M_regfile_rc = 4'h9;
        M_regfile_we = 1'h1;
        out = M_sel_mux_wdsel_out;
        M_phase_d = RESETCOUNTER_phase;
      end
      RESETCOUNTER_phase: begin
        seg_out = 20'ha5281;
        M_regfile_ra = 4'h0;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 2'h1;
        M_sel_mux_bsel_signal = 4'h0;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h1a;
        M_regfile_rc = 4'hc;
        M_regfile_we = 1'h1;
        out = M_sel_mux_wdsel_out;
        M_phase_d = RESETLEDCOLOUR_phase;
      end
      RESETLEDCOLOUR_phase: begin
        seg_out = 20'h0520c;
        M_regfile_ra = 4'h0;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 3'h5;
        M_sel_mux_bsel_signal = 4'h0;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h1a;
        M_regfile_rc = 4'he;
        M_regfile_we = 1'h1;
        out = M_sel_mux_wdsel_out;
        M_phase_d = RESETXORHELPER_phase;
      end
      RESETXORHELPER_phase: begin
        seg_out = 20'h5294e;
        M_regfile_ra = 4'h0;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 3'h6;
        M_sel_mux_bsel_signal = 4'h0;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h1a;
        M_regfile_rc = 4'hd;
        M_regfile_we = 1'h1;
        out = M_sel_mux_wdsel_out;
        M_phase_d = RESETGUESS_phase;
      end
      RESETGUESS_phase: begin
        seg_out = 20'h52946;
        M_regfile_ra = 4'h0;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 3'h5;
        M_sel_mux_bsel_signal = 4'h0;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h1a;
        M_regfile_rc = 4'h7;
        M_regfile_we = 1'h1;
        out = M_sel_mux_wdsel_out;
        M_phase_d = POSITION_phase;
      end
      LOSE_phase: begin
        seg_out = 20'h8024d;
        if (M_slow_edge_out) begin
          M_phase_d = GAMEOVER_phase;
        end
      end
      WIN_phase: begin
        seg_out = 20'h9aa52;
        if (M_slow_edge_out) begin
          M_phase_d = GAMEOVER_phase;
        end
      end
      GAMEOVER_phase: begin
        seg_out = 20'h8864e;
        if (M_slow_edge_out) begin
          M_phase_d = RESETATTEMPT_phase;
        end
      end
      RESETATTEMPT_phase: begin
        seg_out = 20'h5294a;
        M_regfile_ra = 4'h0;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 3'h7;
        M_sel_mux_bsel_signal = 3'h0;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h1a;
        M_regfile_rc = 4'h3;
        M_regfile_we = 1'h1;
        out = M_sel_mux_wdsel_out;
        M_phase_d = RESETALLLED_phase;
      end
      RESETALLLED_phase: begin
        seg_out = 20'h52950;
        M_regfile_ra = 4'h0;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 3'h2;
        M_sel_mux_bsel_signal = 4'he;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h1a;
        M_regfile_rc = 4'h0;
        M_regfile_we = 1'h0;
        M_led_out_encode = {5'h10{{M_sel_mux_asel_out}}};
        out = M_sel_mux_wdsel_out;
        for (index = 1'h0; index < 5'h10; index = index + 1) begin
          M_led_out_update[(index)*1+0-:1] = M_sel_mux_bsel_out[(index)*1+0-:1];
        end
        M_phase_d = RESETGAMEMODE_phase;
      end
      RESETGAMEMODE_phase: begin
        seg_out = 20'h528ce;
        M_regfile_ra = 4'h0;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 3'h2;
        M_sel_mux_bsel_signal = 4'he;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h1a;
        M_regfile_rc = 4'h4;
        M_regfile_we = 1'h1;
        M_led_out_encode = {5'h10{{M_sel_mux_asel_out}}};
        out = M_sel_mux_wdsel_out;
        for (index = 1'h0; index < 5'h10; index = index + 1) begin
          M_led_out_update[(index)*1+0-:1] = M_sel_mux_bsel_out[(index)*1+0-:1];
        end
        M_phase_d = RESETPOSITIONFINAL_phase;
      end
      RESETPOSITIONFINAL_phase: begin
        seg_out = 20'ha5281;
        M_regfile_ra = 4'h0;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 2'h2;
        M_sel_mux_bsel_signal = 4'h0;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h1a;
        M_regfile_rc = 4'h1;
        M_regfile_we = 1'h1;
        out = M_sel_mux_wdsel_out;
        M_phase_d = RESETCOLOURFINAL_phase;
      end
      RESETCOLOURFINAL_phase: begin
        seg_out = 20'ha5282;
        M_regfile_ra = 4'h0;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 2'h3;
        M_sel_mux_bsel_signal = 4'h0;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h1a;
        M_regfile_rc = 4'h2;
        M_regfile_we = 1'h1;
        out = M_sel_mux_wdsel_out;
        M_phase_d = RESETHINTFINAL_phase;
      end
      RESETHINTFINAL_phase: begin
        seg_out = 20'ha5283;
        M_regfile_ra = 4'h0;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 2'h2;
        M_sel_mux_bsel_signal = 4'h0;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h1a;
        M_regfile_rc = 4'h9;
        M_regfile_we = 1'h1;
        out = M_sel_mux_wdsel_out;
        M_phase_d = RESETCOUNTERFINAL_phase;
      end
      RESETCOUNTERFINAL_phase: begin
        seg_out = 20'ha5281;
        M_regfile_ra = 4'h0;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 2'h1;
        M_sel_mux_bsel_signal = 4'h0;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h1a;
        M_regfile_rc = 4'hc;
        M_regfile_we = 1'h1;
        out = M_sel_mux_wdsel_out;
        M_phase_d = RESETLEDCOLOURFINAL_phase;
      end
      RESETLEDCOLOURFINAL_phase: begin
        seg_out = 20'h0520c;
        M_regfile_ra = 4'h0;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 3'h5;
        M_sel_mux_bsel_signal = 4'h0;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h1a;
        M_regfile_rc = 4'he;
        M_regfile_we = 1'h1;
        out = M_sel_mux_wdsel_out;
        M_phase_d = RESETXORHELPERFINAL_phase;
      end
      RESETXORHELPERFINAL_phase: begin
        seg_out = 20'h5294e;
        M_regfile_ra = 4'h0;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 3'h6;
        M_sel_mux_bsel_signal = 4'h0;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h1a;
        M_regfile_rc = 4'hd;
        M_regfile_we = 1'h1;
        out = M_sel_mux_wdsel_out;
        M_phase_d = RESETGUESSFINAL_phase;
      end
      RESETGUESSFINAL_phase: begin
        seg_out = 20'h52946;
        M_regfile_ra = 4'h0;
        M_regfile_rb = 4'h0;
        M_sel_mux_asel_signal = 3'h5;
        M_sel_mux_bsel_signal = 4'h0;
        M_sel_mux_wdsel_signal = 2'h0;
        M_alu16_alufn_signal = 6'h1a;
        M_regfile_rc = 4'h7;
        M_regfile_we = 1'h1;
        out = M_sel_mux_wdsel_out;
        M_phase_d = IDLE_phase;
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_phase_q <= 1'h0;
    end else begin
      M_phase_q <= M_phase_d;
    end
  end
  
endmodule
