/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder_15 (
    input clk,
    input rst,
    input [15:0] a,
    input [15:0] b,
    input [5:0] alufn_op,
    output reg [0:0] z,
    output reg [0:0] v,
    output reg [0:0] n,
    output reg [15:0] out
  );
  
  
  
  reg [15:0] s;
  
  always @* begin
    s = 16'h0000;
    if (alufn_op[0+0-:1] == 1'h0) begin
      s = a + b;
    end
    if (alufn_op[0+0-:1] == 1'h1) begin
      s = a - b;
    end
    n = s[15+0-:1];
    v = (a[15+0-:1] & (b[15+0-:1] ^ alufn_op[0+0-:1]) & !s[15+0-:1]) | (!a[15+0-:1] & !(b[15+0-:1] ^ alufn_op[0+0-:1]) & s[15+0-:1]);
    z = 1'h0;
    if (s == 16'h0000) begin
      z = 1'h1;
    end
    out = s;
  end
endmodule
