/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module external_error_9 (
    input clk,
    input rst,
    input [7:0] inv_input,
    input [15:0] alu_result,
    output reg [15:0] out
  );
  
  
  
  always @* begin
    if (inv_input != 8'h00) begin
      out = alu_result ^ inv_input;
    end else begin
      out = alu_result;
    end
  end
endmodule
